# Static linking with musl libc
panic = "abort"
strip = "symbols"

# Cargo
[cargo]
target_triple = "x86_64-unknown-linux-musl"
target_dir = "{name}-{hash}"
profile = "release"

[rustc]
opt_level = "z"                            # "0", "1", "2", "3", "s", "z"
#panic = "abort"                            # "abort", "unwind", "immediate-abort" (prefer top-level panic)
codegen_units = 1

[linker]
args = ["-static", "-nostdlib"]
